name: assignment
on: push

jobs:
  build:
    name: Run the exam action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./exam
        with:
          N_INDEX: 12

